# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Neko/Desktop/KittyOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Neko/Desktop/KittyOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Neko/Desktop/KittyOS/CMakeFiles /mnt/c/Users/Neko/Desktop/KittyOS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Neko/Desktop/KittyOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KittyOS

# Build rule for target.
KittyOS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KittyOS
.PHONY : KittyOS

# fast build rule for target.
KittyOS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/build
.PHONY : KittyOS/fast

#=============================================================================
# Target rules for targets named PostBuild

# Build rule for target.
PostBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PostBuild
.PHONY : PostBuild

# fast build rule for target.
PostBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PostBuild.dir/build.make CMakeFiles/PostBuild.dir/build
.PHONY : PostBuild/fast

#=============================================================================
# Target rules for targets named PerformAll

# Build rule for target.
PerformAll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PerformAll
.PHONY : PerformAll

# fast build rule for target.
PerformAll/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerformAll.dir/build.make CMakeFiles/PerformAll.dir/build
.PHONY : PerformAll/fast

src/acpi/acpi.o: src/acpi/acpi.cpp.o
.PHONY : src/acpi/acpi.o

# target to build an object file
src/acpi/acpi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/acpi/acpi.cpp.o
.PHONY : src/acpi/acpi.cpp.o

src/acpi/acpi.i: src/acpi/acpi.cpp.i
.PHONY : src/acpi/acpi.i

# target to preprocess a source file
src/acpi/acpi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/acpi/acpi.cpp.i
.PHONY : src/acpi/acpi.cpp.i

src/acpi/acpi.s: src/acpi/acpi.cpp.s
.PHONY : src/acpi/acpi.s

# target to generate assembly for a file
src/acpi/acpi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/acpi/acpi.cpp.s
.PHONY : src/acpi/acpi.cpp.s

src/dbg/log.o: src/dbg/log.cpp.o
.PHONY : src/dbg/log.o

# target to build an object file
src/dbg/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/dbg/log.cpp.o
.PHONY : src/dbg/log.cpp.o

src/dbg/log.i: src/dbg/log.cpp.i
.PHONY : src/dbg/log.i

# target to preprocess a source file
src/dbg/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/dbg/log.cpp.i
.PHONY : src/dbg/log.cpp.i

src/dbg/log.s: src/dbg/log.cpp.s
.PHONY : src/dbg/log.s

# target to generate assembly for a file
src/dbg/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/dbg/log.cpp.s
.PHONY : src/dbg/log.cpp.s

src/hal/apic/apic.o: src/hal/apic/apic.cpp.o
.PHONY : src/hal/apic/apic.o

# target to build an object file
src/hal/apic/apic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/apic/apic.cpp.o
.PHONY : src/hal/apic/apic.cpp.o

src/hal/apic/apic.i: src/hal/apic/apic.cpp.i
.PHONY : src/hal/apic/apic.i

# target to preprocess a source file
src/hal/apic/apic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/apic/apic.cpp.i
.PHONY : src/hal/apic/apic.cpp.i

src/hal/apic/apic.s: src/hal/apic/apic.cpp.s
.PHONY : src/hal/apic/apic.s

# target to generate assembly for a file
src/hal/apic/apic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/apic/apic.cpp.s
.PHONY : src/hal/apic/apic.cpp.s

src/hal/gdt/gdt.o: src/hal/gdt/gdt.cpp.o
.PHONY : src/hal/gdt/gdt.o

# target to build an object file
src/hal/gdt/gdt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/gdt/gdt.cpp.o
.PHONY : src/hal/gdt/gdt.cpp.o

src/hal/gdt/gdt.i: src/hal/gdt/gdt.cpp.i
.PHONY : src/hal/gdt/gdt.i

# target to preprocess a source file
src/hal/gdt/gdt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/gdt/gdt.cpp.i
.PHONY : src/hal/gdt/gdt.cpp.i

src/hal/gdt/gdt.s: src/hal/gdt/gdt.cpp.s
.PHONY : src/hal/gdt/gdt.s

# target to generate assembly for a file
src/hal/gdt/gdt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/gdt/gdt.cpp.s
.PHONY : src/hal/gdt/gdt.cpp.s

src/hal/gdt/load_gdt.o: src/hal/gdt/load_gdt.asm.o
.PHONY : src/hal/gdt/load_gdt.o

# target to build an object file
src/hal/gdt/load_gdt.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/gdt/load_gdt.asm.o
.PHONY : src/hal/gdt/load_gdt.asm.o

src/hal/idt/idt.o: src/hal/idt/idt.cpp.o
.PHONY : src/hal/idt/idt.o

# target to build an object file
src/hal/idt/idt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/idt.cpp.o
.PHONY : src/hal/idt/idt.cpp.o

src/hal/idt/idt.i: src/hal/idt/idt.cpp.i
.PHONY : src/hal/idt/idt.i

# target to preprocess a source file
src/hal/idt/idt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/idt.cpp.i
.PHONY : src/hal/idt/idt.cpp.i

src/hal/idt/idt.s: src/hal/idt/idt.cpp.s
.PHONY : src/hal/idt/idt.s

# target to generate assembly for a file
src/hal/idt/idt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/idt.cpp.s
.PHONY : src/hal/idt/idt.cpp.s

src/hal/idt/idt_table.o: src/hal/idt/idt_table.cpp.o
.PHONY : src/hal/idt/idt_table.o

# target to build an object file
src/hal/idt/idt_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/idt_table.cpp.o
.PHONY : src/hal/idt/idt_table.cpp.o

src/hal/idt/idt_table.i: src/hal/idt/idt_table.cpp.i
.PHONY : src/hal/idt/idt_table.i

# target to preprocess a source file
src/hal/idt/idt_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/idt_table.cpp.i
.PHONY : src/hal/idt/idt_table.cpp.i

src/hal/idt/idt_table.s: src/hal/idt/idt_table.cpp.s
.PHONY : src/hal/idt/idt_table.s

# target to generate assembly for a file
src/hal/idt/idt_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/idt_table.cpp.s
.PHONY : src/hal/idt/idt_table.cpp.s

src/hal/idt/load_idt.o: src/hal/idt/load_idt.asm.o
.PHONY : src/hal/idt/load_idt.o

# target to build an object file
src/hal/idt/load_idt.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/idt/load_idt.asm.o
.PHONY : src/hal/idt/load_idt.asm.o

src/hal/ioapic/ioapic.o: src/hal/ioapic/ioapic.cpp.o
.PHONY : src/hal/ioapic/ioapic.o

# target to build an object file
src/hal/ioapic/ioapic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/ioapic/ioapic.cpp.o
.PHONY : src/hal/ioapic/ioapic.cpp.o

src/hal/ioapic/ioapic.i: src/hal/ioapic/ioapic.cpp.i
.PHONY : src/hal/ioapic/ioapic.i

# target to preprocess a source file
src/hal/ioapic/ioapic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/ioapic/ioapic.cpp.i
.PHONY : src/hal/ioapic/ioapic.cpp.i

src/hal/ioapic/ioapic.s: src/hal/ioapic/ioapic.cpp.s
.PHONY : src/hal/ioapic/ioapic.s

# target to generate assembly for a file
src/hal/ioapic/ioapic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/ioapic/ioapic.cpp.s
.PHONY : src/hal/ioapic/ioapic.cpp.s

src/hal/irq/irq.o: src/hal/irq/irq.cpp.o
.PHONY : src/hal/irq/irq.o

# target to build an object file
src/hal/irq/irq.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/irq/irq.cpp.o
.PHONY : src/hal/irq/irq.cpp.o

src/hal/irq/irq.i: src/hal/irq/irq.cpp.i
.PHONY : src/hal/irq/irq.i

# target to preprocess a source file
src/hal/irq/irq.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/irq/irq.cpp.i
.PHONY : src/hal/irq/irq.cpp.i

src/hal/irq/irq.s: src/hal/irq/irq.cpp.s
.PHONY : src/hal/irq/irq.s

# target to generate assembly for a file
src/hal/irq/irq.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/hal/irq/irq.cpp.s
.PHONY : src/hal/irq/irq.cpp.s

src/lib/klibc/runtime-blob.o: src/lib/klibc/runtime-blob.cpp.o
.PHONY : src/lib/klibc/runtime-blob.o

# target to build an object file
src/lib/klibc/runtime-blob.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/klibc/runtime-blob.cpp.o
.PHONY : src/lib/klibc/runtime-blob.cpp.o

src/lib/klibc/runtime-blob.i: src/lib/klibc/runtime-blob.cpp.i
.PHONY : src/lib/klibc/runtime-blob.i

# target to preprocess a source file
src/lib/klibc/runtime-blob.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/klibc/runtime-blob.cpp.i
.PHONY : src/lib/klibc/runtime-blob.cpp.i

src/lib/klibc/runtime-blob.s: src/lib/klibc/runtime-blob.cpp.s
.PHONY : src/lib/klibc/runtime-blob.s

# target to generate assembly for a file
src/lib/klibc/runtime-blob.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/klibc/runtime-blob.cpp.s
.PHONY : src/lib/klibc/runtime-blob.cpp.s

src/lib/npf/nanoprintf.o: src/lib/npf/nanoprintf.cpp.o
.PHONY : src/lib/npf/nanoprintf.o

# target to build an object file
src/lib/npf/nanoprintf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/npf/nanoprintf.cpp.o
.PHONY : src/lib/npf/nanoprintf.cpp.o

src/lib/npf/nanoprintf.i: src/lib/npf/nanoprintf.cpp.i
.PHONY : src/lib/npf/nanoprintf.i

# target to preprocess a source file
src/lib/npf/nanoprintf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/npf/nanoprintf.cpp.i
.PHONY : src/lib/npf/nanoprintf.cpp.i

src/lib/npf/nanoprintf.s: src/lib/npf/nanoprintf.cpp.s
.PHONY : src/lib/npf/nanoprintf.s

# target to generate assembly for a file
src/lib/npf/nanoprintf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/npf/nanoprintf.cpp.s
.PHONY : src/lib/npf/nanoprintf.cpp.s

src/lib/xxHash/xxh_x86dispatch.o: src/lib/xxHash/xxh_x86dispatch.c.o
.PHONY : src/lib/xxHash/xxh_x86dispatch.o

# target to build an object file
src/lib/xxHash/xxh_x86dispatch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/xxHash/xxh_x86dispatch.c.o
.PHONY : src/lib/xxHash/xxh_x86dispatch.c.o

src/lib/xxHash/xxh_x86dispatch.i: src/lib/xxHash/xxh_x86dispatch.c.i
.PHONY : src/lib/xxHash/xxh_x86dispatch.i

# target to preprocess a source file
src/lib/xxHash/xxh_x86dispatch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/xxHash/xxh_x86dispatch.c.i
.PHONY : src/lib/xxHash/xxh_x86dispatch.c.i

src/lib/xxHash/xxh_x86dispatch.s: src/lib/xxHash/xxh_x86dispatch.c.s
.PHONY : src/lib/xxHash/xxh_x86dispatch.s

# target to generate assembly for a file
src/lib/xxHash/xxh_x86dispatch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/xxHash/xxh_x86dispatch.c.s
.PHONY : src/lib/xxHash/xxh_x86dispatch.c.s

src/lib/xxHash/xxhash.o: src/lib/xxHash/xxhash.c.o
.PHONY : src/lib/xxHash/xxhash.o

# target to build an object file
src/lib/xxHash/xxhash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/xxHash/xxhash.c.o
.PHONY : src/lib/xxHash/xxhash.c.o

src/lib/xxHash/xxhash.i: src/lib/xxHash/xxhash.c.i
.PHONY : src/lib/xxHash/xxhash.i

# target to preprocess a source file
src/lib/xxHash/xxhash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/xxHash/xxhash.c.i
.PHONY : src/lib/xxHash/xxhash.c.i

src/lib/xxHash/xxhash.s: src/lib/xxHash/xxhash.c.s
.PHONY : src/lib/xxHash/xxhash.s

# target to generate assembly for a file
src/lib/xxHash/xxhash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/lib/xxHash/xxhash.c.s
.PHONY : src/lib/xxHash/xxhash.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mem/heap.o: src/mem/heap.cpp.o
.PHONY : src/mem/heap.o

# target to build an object file
src/mem/heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/heap.cpp.o
.PHONY : src/mem/heap.cpp.o

src/mem/heap.i: src/mem/heap.cpp.i
.PHONY : src/mem/heap.i

# target to preprocess a source file
src/mem/heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/heap.cpp.i
.PHONY : src/mem/heap.cpp.i

src/mem/heap.s: src/mem/heap.cpp.s
.PHONY : src/mem/heap.s

# target to generate assembly for a file
src/mem/heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/heap.cpp.s
.PHONY : src/mem/heap.cpp.s

src/mem/malloc.o: src/mem/malloc.c.o
.PHONY : src/mem/malloc.o

# target to build an object file
src/mem/malloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/malloc.c.o
.PHONY : src/mem/malloc.c.o

src/mem/malloc.i: src/mem/malloc.c.i
.PHONY : src/mem/malloc.i

# target to preprocess a source file
src/mem/malloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/malloc.c.i
.PHONY : src/mem/malloc.c.i

src/mem/malloc.s: src/mem/malloc.c.s
.PHONY : src/mem/malloc.s

# target to generate assembly for a file
src/mem/malloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/malloc.c.s
.PHONY : src/mem/malloc.c.s

src/mem/physical.o: src/mem/physical.cpp.o
.PHONY : src/mem/physical.o

# target to build an object file
src/mem/physical.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/physical.cpp.o
.PHONY : src/mem/physical.cpp.o

src/mem/physical.i: src/mem/physical.cpp.i
.PHONY : src/mem/physical.i

# target to preprocess a source file
src/mem/physical.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/physical.cpp.i
.PHONY : src/mem/physical.cpp.i

src/mem/physical.s: src/mem/physical.cpp.s
.PHONY : src/mem/physical.s

# target to generate assembly for a file
src/mem/physical.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/physical.cpp.s
.PHONY : src/mem/physical.cpp.s

src/mem/virtual.o: src/mem/virtual.cpp.o
.PHONY : src/mem/virtual.o

# target to build an object file
src/mem/virtual.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/virtual.cpp.o
.PHONY : src/mem/virtual.cpp.o

src/mem/virtual.i: src/mem/virtual.cpp.i
.PHONY : src/mem/virtual.i

# target to preprocess a source file
src/mem/virtual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/virtual.cpp.i
.PHONY : src/mem/virtual.cpp.i

src/mem/virtual.s: src/mem/virtual.cpp.s
.PHONY : src/mem/virtual.s

# target to generate assembly for a file
src/mem/virtual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/mem/virtual.cpp.s
.PHONY : src/mem/virtual.cpp.s

src/smp/smp.o: src/smp/smp.cpp.o
.PHONY : src/smp/smp.o

# target to build an object file
src/smp/smp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/smp/smp.cpp.o
.PHONY : src/smp/smp.cpp.o

src/smp/smp.i: src/smp/smp.cpp.i
.PHONY : src/smp/smp.i

# target to preprocess a source file
src/smp/smp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/smp/smp.cpp.i
.PHONY : src/smp/smp.cpp.i

src/smp/smp.s: src/smp/smp.cpp.s
.PHONY : src/smp/smp.s

# target to generate assembly for a file
src/smp/smp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/smp/smp.cpp.s
.PHONY : src/smp/smp.cpp.s

src/start.o: src/start.asm.o
.PHONY : src/start.o

# target to build an object file
src/start.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KittyOS.dir/build.make CMakeFiles/KittyOS.dir/src/start.asm.o
.PHONY : src/start.asm.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PerformAll"
	@echo "... PostBuild"
	@echo "... KittyOS"
	@echo "... src/acpi/acpi.o"
	@echo "... src/acpi/acpi.i"
	@echo "... src/acpi/acpi.s"
	@echo "... src/dbg/log.o"
	@echo "... src/dbg/log.i"
	@echo "... src/dbg/log.s"
	@echo "... src/hal/apic/apic.o"
	@echo "... src/hal/apic/apic.i"
	@echo "... src/hal/apic/apic.s"
	@echo "... src/hal/gdt/gdt.o"
	@echo "... src/hal/gdt/gdt.i"
	@echo "... src/hal/gdt/gdt.s"
	@echo "... src/hal/gdt/load_gdt.o"
	@echo "... src/hal/idt/idt.o"
	@echo "... src/hal/idt/idt.i"
	@echo "... src/hal/idt/idt.s"
	@echo "... src/hal/idt/idt_table.o"
	@echo "... src/hal/idt/idt_table.i"
	@echo "... src/hal/idt/idt_table.s"
	@echo "... src/hal/idt/load_idt.o"
	@echo "... src/hal/ioapic/ioapic.o"
	@echo "... src/hal/ioapic/ioapic.i"
	@echo "... src/hal/ioapic/ioapic.s"
	@echo "... src/hal/irq/irq.o"
	@echo "... src/hal/irq/irq.i"
	@echo "... src/hal/irq/irq.s"
	@echo "... src/lib/klibc/runtime-blob.o"
	@echo "... src/lib/klibc/runtime-blob.i"
	@echo "... src/lib/klibc/runtime-blob.s"
	@echo "... src/lib/npf/nanoprintf.o"
	@echo "... src/lib/npf/nanoprintf.i"
	@echo "... src/lib/npf/nanoprintf.s"
	@echo "... src/lib/xxHash/xxh_x86dispatch.o"
	@echo "... src/lib/xxHash/xxh_x86dispatch.i"
	@echo "... src/lib/xxHash/xxh_x86dispatch.s"
	@echo "... src/lib/xxHash/xxhash.o"
	@echo "... src/lib/xxHash/xxhash.i"
	@echo "... src/lib/xxHash/xxhash.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mem/heap.o"
	@echo "... src/mem/heap.i"
	@echo "... src/mem/heap.s"
	@echo "... src/mem/malloc.o"
	@echo "... src/mem/malloc.i"
	@echo "... src/mem/malloc.s"
	@echo "... src/mem/physical.o"
	@echo "... src/mem/physical.i"
	@echo "... src/mem/physical.s"
	@echo "... src/mem/virtual.o"
	@echo "... src/mem/virtual.i"
	@echo "... src/mem/virtual.s"
	@echo "... src/smp/smp.o"
	@echo "... src/smp/smp.i"
	@echo "... src/smp/smp.s"
	@echo "... src/start.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

